// flow-typed signature: 14fdc72547a04deeed903ee9541b7a21
// flow-typed version: <<STUB>>/@uifabric/react-cards_v^0.107.7/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uifabric/react-cards'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uifabric/react-cards' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@uifabric/react-cards/config/tests' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/0.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/1.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/10.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/11.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/12.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/13.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/14.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/15.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/16.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/17.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/18.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/19.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/2.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/20.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/21.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/22.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/23.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/24.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/25.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/26.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/27.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/28.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/29.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/3.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/30.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/31.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/32.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/33.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/34.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/35.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/36.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/37.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/38.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/39.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/4.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/40.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/41.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/42.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/43.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/44.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/45.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/46.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/47.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/48.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/49.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/5.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/50.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/51.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/52.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/53.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/54.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/55.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/56.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/57.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/58.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/6.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/7.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/8.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/9.demo-app' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/react-cards' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/react-cards.min' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/react-dom.development' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/dist/react.development' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/Card' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/components/Card/Card.doc' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/components/Card/Card' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/components/Card/Card.styles' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/components/Card/Card.types' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/components/Card/Card.view' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/components/Card/CardItem/CardItem' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/components/Card/CardItem/CardItem.styles' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/components/Card/CardItem/CardItem.types' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/components/Card/CardItem/CardItem.view' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/components/Card/CardPage' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/components/Card/CardSection/CardSection' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/components/Card/CardSection/CardSection.styles' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/components/Card/CardSection/CardSection.types' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/components/Card/CardSection/CardSection.view' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/components/Card/examples/Card.Compact.Example' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/components/Card/examples/Card.Configure.Example' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/components/Card/examples/Card.Vertical.Example' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/components/Card/index' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/demo/AppDefinition' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/demo/customizations' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/demo/GettingStartedPage' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/demo/index' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/index' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-amd/version' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/Card' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/components/Card/Card.doc' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/components/Card/Card' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/components/Card/Card.styles' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/components/Card/Card.types' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/components/Card/Card.view' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/components/Card/CardItem/CardItem' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/components/Card/CardItem/CardItem.styles' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/components/Card/CardItem/CardItem.types' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/components/Card/CardItem/CardItem.view' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/components/Card/CardPage' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/components/Card/CardSection/CardSection' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/components/Card/CardSection/CardSection.styles' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/components/Card/CardSection/CardSection.types' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/components/Card/CardSection/CardSection.view' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/components/Card/examples/Card.Compact.Example' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/components/Card/examples/Card.Configure.Example' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/components/Card/examples/Card.Vertical.Example' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/components/Card/index' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/demo/AppDefinition' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/demo/customizations' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/demo/GettingStartedPage' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/demo/index' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/index' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib-commonjs/version' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/Card' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/components/Card/Card.doc' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/components/Card/Card' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/components/Card/Card.styles' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/components/Card/Card.types' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/components/Card/Card.view' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/components/Card/CardItem/CardItem' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/components/Card/CardItem/CardItem.styles' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/components/Card/CardItem/CardItem.types' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/components/Card/CardItem/CardItem.view' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/components/Card/CardPage' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/components/Card/CardSection/CardSection' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/components/Card/CardSection/CardSection.styles' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/components/Card/CardSection/CardSection.types' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/components/Card/CardSection/CardSection.view' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/components/Card/examples/Card.Compact.Example' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/components/Card/examples/Card.Configure.Example' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/components/Card/examples/Card.Vertical.Example' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/components/Card/index' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/demo/AppDefinition' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/demo/customizations' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/demo/GettingStartedPage' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/demo/index' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/index' {
  declare module.exports: any;
}

declare module '@uifabric/react-cards/lib/version' {
  declare module.exports: any;
}

// Filename aliases
declare module '@uifabric/react-cards/config/tests.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/config/tests'>;
}
declare module '@uifabric/react-cards/dist/0.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/0.demo-app'>;
}
declare module '@uifabric/react-cards/dist/1.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/1.demo-app'>;
}
declare module '@uifabric/react-cards/dist/10.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/10.demo-app'>;
}
declare module '@uifabric/react-cards/dist/11.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/11.demo-app'>;
}
declare module '@uifabric/react-cards/dist/12.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/12.demo-app'>;
}
declare module '@uifabric/react-cards/dist/13.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/13.demo-app'>;
}
declare module '@uifabric/react-cards/dist/14.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/14.demo-app'>;
}
declare module '@uifabric/react-cards/dist/15.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/15.demo-app'>;
}
declare module '@uifabric/react-cards/dist/16.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/16.demo-app'>;
}
declare module '@uifabric/react-cards/dist/17.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/17.demo-app'>;
}
declare module '@uifabric/react-cards/dist/18.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/18.demo-app'>;
}
declare module '@uifabric/react-cards/dist/19.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/19.demo-app'>;
}
declare module '@uifabric/react-cards/dist/2.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/2.demo-app'>;
}
declare module '@uifabric/react-cards/dist/20.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/20.demo-app'>;
}
declare module '@uifabric/react-cards/dist/21.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/21.demo-app'>;
}
declare module '@uifabric/react-cards/dist/22.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/22.demo-app'>;
}
declare module '@uifabric/react-cards/dist/23.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/23.demo-app'>;
}
declare module '@uifabric/react-cards/dist/24.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/24.demo-app'>;
}
declare module '@uifabric/react-cards/dist/25.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/25.demo-app'>;
}
declare module '@uifabric/react-cards/dist/26.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/26.demo-app'>;
}
declare module '@uifabric/react-cards/dist/27.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/27.demo-app'>;
}
declare module '@uifabric/react-cards/dist/28.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/28.demo-app'>;
}
declare module '@uifabric/react-cards/dist/29.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/29.demo-app'>;
}
declare module '@uifabric/react-cards/dist/3.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/3.demo-app'>;
}
declare module '@uifabric/react-cards/dist/30.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/30.demo-app'>;
}
declare module '@uifabric/react-cards/dist/31.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/31.demo-app'>;
}
declare module '@uifabric/react-cards/dist/32.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/32.demo-app'>;
}
declare module '@uifabric/react-cards/dist/33.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/33.demo-app'>;
}
declare module '@uifabric/react-cards/dist/34.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/34.demo-app'>;
}
declare module '@uifabric/react-cards/dist/35.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/35.demo-app'>;
}
declare module '@uifabric/react-cards/dist/36.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/36.demo-app'>;
}
declare module '@uifabric/react-cards/dist/37.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/37.demo-app'>;
}
declare module '@uifabric/react-cards/dist/38.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/38.demo-app'>;
}
declare module '@uifabric/react-cards/dist/39.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/39.demo-app'>;
}
declare module '@uifabric/react-cards/dist/4.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/4.demo-app'>;
}
declare module '@uifabric/react-cards/dist/40.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/40.demo-app'>;
}
declare module '@uifabric/react-cards/dist/41.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/41.demo-app'>;
}
declare module '@uifabric/react-cards/dist/42.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/42.demo-app'>;
}
declare module '@uifabric/react-cards/dist/43.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/43.demo-app'>;
}
declare module '@uifabric/react-cards/dist/44.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/44.demo-app'>;
}
declare module '@uifabric/react-cards/dist/45.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/45.demo-app'>;
}
declare module '@uifabric/react-cards/dist/46.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/46.demo-app'>;
}
declare module '@uifabric/react-cards/dist/47.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/47.demo-app'>;
}
declare module '@uifabric/react-cards/dist/48.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/48.demo-app'>;
}
declare module '@uifabric/react-cards/dist/49.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/49.demo-app'>;
}
declare module '@uifabric/react-cards/dist/5.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/5.demo-app'>;
}
declare module '@uifabric/react-cards/dist/50.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/50.demo-app'>;
}
declare module '@uifabric/react-cards/dist/51.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/51.demo-app'>;
}
declare module '@uifabric/react-cards/dist/52.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/52.demo-app'>;
}
declare module '@uifabric/react-cards/dist/53.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/53.demo-app'>;
}
declare module '@uifabric/react-cards/dist/54.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/54.demo-app'>;
}
declare module '@uifabric/react-cards/dist/55.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/55.demo-app'>;
}
declare module '@uifabric/react-cards/dist/56.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/56.demo-app'>;
}
declare module '@uifabric/react-cards/dist/57.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/57.demo-app'>;
}
declare module '@uifabric/react-cards/dist/58.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/58.demo-app'>;
}
declare module '@uifabric/react-cards/dist/6.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/6.demo-app'>;
}
declare module '@uifabric/react-cards/dist/7.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/7.demo-app'>;
}
declare module '@uifabric/react-cards/dist/8.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/8.demo-app'>;
}
declare module '@uifabric/react-cards/dist/9.demo-app.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/9.demo-app'>;
}
declare module '@uifabric/react-cards/dist/react-cards.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/react-cards'>;
}
declare module '@uifabric/react-cards/dist/react-cards.min.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/react-cards.min'>;
}
declare module '@uifabric/react-cards/dist/react-dom.development.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/react-dom.development'>;
}
declare module '@uifabric/react-cards/dist/react.development.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/dist/react.development'>;
}
declare module '@uifabric/react-cards/lib-amd/Card.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/Card'>;
}
declare module '@uifabric/react-cards/lib-amd/components/Card/Card.doc.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/components/Card/Card.doc'>;
}
declare module '@uifabric/react-cards/lib-amd/components/Card/Card.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/components/Card/Card'>;
}
declare module '@uifabric/react-cards/lib-amd/components/Card/Card.styles.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/components/Card/Card.styles'>;
}
declare module '@uifabric/react-cards/lib-amd/components/Card/Card.types.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/components/Card/Card.types'>;
}
declare module '@uifabric/react-cards/lib-amd/components/Card/Card.view.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/components/Card/Card.view'>;
}
declare module '@uifabric/react-cards/lib-amd/components/Card/CardItem/CardItem.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/components/Card/CardItem/CardItem'>;
}
declare module '@uifabric/react-cards/lib-amd/components/Card/CardItem/CardItem.styles.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/components/Card/CardItem/CardItem.styles'>;
}
declare module '@uifabric/react-cards/lib-amd/components/Card/CardItem/CardItem.types.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/components/Card/CardItem/CardItem.types'>;
}
declare module '@uifabric/react-cards/lib-amd/components/Card/CardItem/CardItem.view.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/components/Card/CardItem/CardItem.view'>;
}
declare module '@uifabric/react-cards/lib-amd/components/Card/CardPage.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/components/Card/CardPage'>;
}
declare module '@uifabric/react-cards/lib-amd/components/Card/CardSection/CardSection.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/components/Card/CardSection/CardSection'>;
}
declare module '@uifabric/react-cards/lib-amd/components/Card/CardSection/CardSection.styles.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/components/Card/CardSection/CardSection.styles'>;
}
declare module '@uifabric/react-cards/lib-amd/components/Card/CardSection/CardSection.types.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/components/Card/CardSection/CardSection.types'>;
}
declare module '@uifabric/react-cards/lib-amd/components/Card/CardSection/CardSection.view.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/components/Card/CardSection/CardSection.view'>;
}
declare module '@uifabric/react-cards/lib-amd/components/Card/examples/Card.Compact.Example.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/components/Card/examples/Card.Compact.Example'>;
}
declare module '@uifabric/react-cards/lib-amd/components/Card/examples/Card.Configure.Example.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/components/Card/examples/Card.Configure.Example'>;
}
declare module '@uifabric/react-cards/lib-amd/components/Card/examples/Card.Vertical.Example.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/components/Card/examples/Card.Vertical.Example'>;
}
declare module '@uifabric/react-cards/lib-amd/components/Card/index.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/components/Card/index'>;
}
declare module '@uifabric/react-cards/lib-amd/demo/AppDefinition.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/demo/AppDefinition'>;
}
declare module '@uifabric/react-cards/lib-amd/demo/customizations.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/demo/customizations'>;
}
declare module '@uifabric/react-cards/lib-amd/demo/GettingStartedPage.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/demo/GettingStartedPage'>;
}
declare module '@uifabric/react-cards/lib-amd/demo/index.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/demo/index'>;
}
declare module '@uifabric/react-cards/lib-amd/index.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/index'>;
}
declare module '@uifabric/react-cards/lib-amd/version.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-amd/version'>;
}
declare module '@uifabric/react-cards/lib-commonjs/Card.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/Card'>;
}
declare module '@uifabric/react-cards/lib-commonjs/components/Card/Card.doc.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/components/Card/Card.doc'>;
}
declare module '@uifabric/react-cards/lib-commonjs/components/Card/Card.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/components/Card/Card'>;
}
declare module '@uifabric/react-cards/lib-commonjs/components/Card/Card.styles.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/components/Card/Card.styles'>;
}
declare module '@uifabric/react-cards/lib-commonjs/components/Card/Card.types.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/components/Card/Card.types'>;
}
declare module '@uifabric/react-cards/lib-commonjs/components/Card/Card.view.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/components/Card/Card.view'>;
}
declare module '@uifabric/react-cards/lib-commonjs/components/Card/CardItem/CardItem.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/components/Card/CardItem/CardItem'>;
}
declare module '@uifabric/react-cards/lib-commonjs/components/Card/CardItem/CardItem.styles.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/components/Card/CardItem/CardItem.styles'>;
}
declare module '@uifabric/react-cards/lib-commonjs/components/Card/CardItem/CardItem.types.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/components/Card/CardItem/CardItem.types'>;
}
declare module '@uifabric/react-cards/lib-commonjs/components/Card/CardItem/CardItem.view.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/components/Card/CardItem/CardItem.view'>;
}
declare module '@uifabric/react-cards/lib-commonjs/components/Card/CardPage.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/components/Card/CardPage'>;
}
declare module '@uifabric/react-cards/lib-commonjs/components/Card/CardSection/CardSection.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/components/Card/CardSection/CardSection'>;
}
declare module '@uifabric/react-cards/lib-commonjs/components/Card/CardSection/CardSection.styles.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/components/Card/CardSection/CardSection.styles'>;
}
declare module '@uifabric/react-cards/lib-commonjs/components/Card/CardSection/CardSection.types.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/components/Card/CardSection/CardSection.types'>;
}
declare module '@uifabric/react-cards/lib-commonjs/components/Card/CardSection/CardSection.view.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/components/Card/CardSection/CardSection.view'>;
}
declare module '@uifabric/react-cards/lib-commonjs/components/Card/examples/Card.Compact.Example.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/components/Card/examples/Card.Compact.Example'>;
}
declare module '@uifabric/react-cards/lib-commonjs/components/Card/examples/Card.Configure.Example.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/components/Card/examples/Card.Configure.Example'>;
}
declare module '@uifabric/react-cards/lib-commonjs/components/Card/examples/Card.Vertical.Example.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/components/Card/examples/Card.Vertical.Example'>;
}
declare module '@uifabric/react-cards/lib-commonjs/components/Card/index.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/components/Card/index'>;
}
declare module '@uifabric/react-cards/lib-commonjs/demo/AppDefinition.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/demo/AppDefinition'>;
}
declare module '@uifabric/react-cards/lib-commonjs/demo/customizations.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/demo/customizations'>;
}
declare module '@uifabric/react-cards/lib-commonjs/demo/GettingStartedPage.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/demo/GettingStartedPage'>;
}
declare module '@uifabric/react-cards/lib-commonjs/demo/index.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/demo/index'>;
}
declare module '@uifabric/react-cards/lib-commonjs/index.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/index'>;
}
declare module '@uifabric/react-cards/lib-commonjs/version.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib-commonjs/version'>;
}
declare module '@uifabric/react-cards/lib/Card.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/Card'>;
}
declare module '@uifabric/react-cards/lib/components/Card/Card.doc.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/components/Card/Card.doc'>;
}
declare module '@uifabric/react-cards/lib/components/Card/Card.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/components/Card/Card'>;
}
declare module '@uifabric/react-cards/lib/components/Card/Card.styles.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/components/Card/Card.styles'>;
}
declare module '@uifabric/react-cards/lib/components/Card/Card.types.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/components/Card/Card.types'>;
}
declare module '@uifabric/react-cards/lib/components/Card/Card.view.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/components/Card/Card.view'>;
}
declare module '@uifabric/react-cards/lib/components/Card/CardItem/CardItem.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/components/Card/CardItem/CardItem'>;
}
declare module '@uifabric/react-cards/lib/components/Card/CardItem/CardItem.styles.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/components/Card/CardItem/CardItem.styles'>;
}
declare module '@uifabric/react-cards/lib/components/Card/CardItem/CardItem.types.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/components/Card/CardItem/CardItem.types'>;
}
declare module '@uifabric/react-cards/lib/components/Card/CardItem/CardItem.view.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/components/Card/CardItem/CardItem.view'>;
}
declare module '@uifabric/react-cards/lib/components/Card/CardPage.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/components/Card/CardPage'>;
}
declare module '@uifabric/react-cards/lib/components/Card/CardSection/CardSection.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/components/Card/CardSection/CardSection'>;
}
declare module '@uifabric/react-cards/lib/components/Card/CardSection/CardSection.styles.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/components/Card/CardSection/CardSection.styles'>;
}
declare module '@uifabric/react-cards/lib/components/Card/CardSection/CardSection.types.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/components/Card/CardSection/CardSection.types'>;
}
declare module '@uifabric/react-cards/lib/components/Card/CardSection/CardSection.view.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/components/Card/CardSection/CardSection.view'>;
}
declare module '@uifabric/react-cards/lib/components/Card/examples/Card.Compact.Example.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/components/Card/examples/Card.Compact.Example'>;
}
declare module '@uifabric/react-cards/lib/components/Card/examples/Card.Configure.Example.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/components/Card/examples/Card.Configure.Example'>;
}
declare module '@uifabric/react-cards/lib/components/Card/examples/Card.Vertical.Example.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/components/Card/examples/Card.Vertical.Example'>;
}
declare module '@uifabric/react-cards/lib/components/Card/index.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/components/Card/index'>;
}
declare module '@uifabric/react-cards/lib/demo/AppDefinition.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/demo/AppDefinition'>;
}
declare module '@uifabric/react-cards/lib/demo/customizations.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/demo/customizations'>;
}
declare module '@uifabric/react-cards/lib/demo/GettingStartedPage.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/demo/GettingStartedPage'>;
}
declare module '@uifabric/react-cards/lib/demo/index.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/demo/index'>;
}
declare module '@uifabric/react-cards/lib/index.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/index'>;
}
declare module '@uifabric/react-cards/lib/version.js' {
  declare module.exports: $Exports<'@uifabric/react-cards/lib/version'>;
}
